### PR TITLE
Fixes #167

### LINKED ISSUE #167: Verify Email Link
Verify email links you to 127.0.0.1 address.

Example from email:
https://127.0.0.1/api/v1/Users/confirm?uid=176&redirect=/&token=x

### PR DESCRIPTION
**Pull request by jcdesimp**
If it was really this easy then shame on us.

### CODE REVIEW

**Comment by kocsenc** [comment]
Hope not that easy. 

This may solve other problems. You had to look for the email body that gets sent out. I think that's only in production however. The email has to change the irk of the a tag in the email to rmc rather tha. Local host.

**Comment by jcdesimp** [comment]
https://github.com/craigcabrey/ratemycoop/blob/dcd1cc066e53ff70305394dfb23330a379729433/server/boot/user-extensions.js#L69

**Comment by jamesa** [comment]
Why wouldn't it be this easy? I found this when we were talking about it a few months ago. Wouldn't you just change this setting on wherever it's deployed?

**Comment by kocsenc** [comment]
Attempting to do that actually caused unexpected behavior from loopback.

**Pull request closed without merging**
