### PR TITLE
Bug/164

### LINKED ISSUE #164: Video seems blocks usage on iOS 7

### PR DESCRIPTION
**Pull request by jcdesimp**
Don't render the video on mobile devices Fixes #164

### CODE REVIEW

**Comment by craigcabrey** [comment]
cleanup all the newlines.

**Comment by jcdesimp** [comment]
@craigcabrey @kocsenc suggested we use ng-if instead, makes more sense really. Did we plan on having multiple sources that would need to be dynamically added that way? ng-if should cover them all either way, right?

**Comment by craigcabrey** [comment]
Does the `ng-if` prevent the node from being inserted into the DOM? If so, I'm fine with using `ng-if`.

**Comment by jcdesimp** [comment]
@craigcabrey newlines removed.

**Comment by kocsenc** [comment]
@craigcabrey `ng-if` is used to prevent the element from being rendered in the dom. `ng-show` has a similar behavior but only applies `hidden`. It's cool beans.

The `ng-repeat` solution was causing performance issues, and not appropriate either.

**Pull request merged**
